---
# tasks file for checkbox
- hosts: all
  become: true
  gather_facts: False


  vars:
    ansible_distribution_release: "xenial"
    mongodb_version: "3.6"
    checkbox_folder: "/home/{{ ansible_user }}/checkbox.io"

  tasks:
  - name: Install node on server
    become: true
    shell: curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -

  - name: Install node on server
    become: true
    apt:
        name: nodejs

  - name: Install npm on server
    become: true
    apt:
        pkg: build-essential
        state: present

  - name: Installing Python pip
    become: true
    apt:
        pkg: python-pip
        state: latest

  - name: Installing Python 3 pip
    become: true
    apt:
        pkg: python3-pip
        state: latest

  - name: Install nginx
    become: true
    apt:
        pkg: nginx
        state: latest
        update_cache: yes

  - name: Add mongo ppa key
    apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
        state: present 
    become: true
    
  - name: Add mongo sources list
    apt_repository:
        repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu {{ansible_distribution_release}}/mongodb-org/{{mongodb_version}} multiverse"
    become: true

  - name: Installing MongoDB
    become: true
    apt: 
        name: mongodb-org
        state: present
        update-cache: yes
        
    # notify:
    #     - start mongodb

  - name: Install the pymongo package
    become: true
    pip: 
        name: pymongo 
        state: latest
        use_mirrors: no

  - name: Start Mongo daemon
    become: true
    service:
        name: mongod
        state: started

  - name: Creating MongoDb user
    become: true
    mongodb_user:
        database: "admin"
        name: "admin"
        password: "root"
        roles: readWrite,dbAdmin
        state: present

  # - name: Checking for already cloned checkbox repository
  #   stat:
  #       path: "{{checkbox_folder}}"
  #   register: checkbox_repo

  - name: Cloning checkbox repository
    become: true
    git:
        repo: "https://github.com/arpitashekhar/checkbox.io.git"
        dest: "{{checkbox_folder}}"
        update: no
        force: yes
    #when: checkbox_repo.stat.isdir is not defined

  - name: Run npm install to install dependencies 
    become: true
    command: npm install
    args:
      chdir: "/home/{{ ansible_user }}/checkbox.io/server-side/site"

  - name: Install packages for New Relic 
    become: true
    command: npm install newrelic --save
    args: 
      chdir: "/home/{{ ansible_user }}/checkbox.io/server-side/site" 

  - name: update location of public_html into default
    become: true
    replace:
        dest: "{{checkbox_folder}}/local-conf/default"
        regexp: "/Users/gameweld/bitbucket/checkbox.io/checkbox.io/public_html"
        replace: "{{checkbox_folder}}/public_html"

  - name: Copy default file to nginx folder
    become: true
    copy: 
        src: "{{checkbox_folder}}/local-conf/default"
        dest: "/etc/nginx/sites-available/default"
        remote_src: true
        mode: 0644

  - name: Copy nginx.conf file to diferent location
    become: true
    copy: 
        src: "{{checkbox_folder}}/local-conf/nginx.conf" 
        dest: "/etc/nginx/nginx.conf"
        remote_src: true
        mode: 0644

  - name: Transfer newrelic.js template
    become: true
    template:
      src: "/home/{{ ansible_user }}/deploy-instances/templates/newrelic.js"
      dest: "{{checkbox_folder}}/server-side/site/newrelic.js"
      force: yes

  # - name: line insert
  #   become: true
  #   lineinfile:
  #     path: "{{checkbox_folder}}/server-side/site/server.js"
  #     line: require('newrelic');
  #     insertbefore: BOF

  - name: Install forever (to run Node.js app)
    become: true
    npm: 
        name: forever 
        global: yes 
        state: present

  - name: "Check list of Node.js apps running."
    become: true
    command: forever list
    register: forever_list
    changed_when: false
        
  - name: Start application
    become: true
    command: forever start {{checkbox_folder}}/server-side/site/server.js
    when: "forever_list.stdout.find('/home/{{ansible_user}}/checkbox.io/server-side/site/server.js') == -1"

  - name: Restart nginx
    become: true
    service: 
        name: nginx 
        state: restarted 
        enabled: yes
